Repository momentobooth/momentobooth, pull requests merged in 2023-04, with the labels that each got.

#49 Allow setting full screen mode.
  lib/main.dart
  lib/views/settings_screen/settings_screen_view.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: enhancement

#52 Templates & IO
  lib/managers/photos_manager.dart
  lib/models/settings.dart
  lib/views/capture_screen/capture_screen_view.dart
  lib/views/capture_screen/capture_screen_view_model.dart
  lib/views/collage_maker_screen/collage_maker_screen_controller.dart
  lib/views/collage_maker_screen/collage_maker_screen_view.dart
  lib/views/custom_widgets/photo_collage.dart
  lib/views/settings_screen/settings_screen_controller.dart
  lib/views/settings_screen/settings_screen_view.dart
  lib/views/settings_screen/settings_screen_view.helpers.dart
  lib/views/settings_screen/settings_screen_view_model.dart
  lib/views/share_screen/share_screen_controller.dart
  lib/views/share_screen/share_screen_view.dart
  lib/views/share_screen/share_screen_view_model.dart
  lib/views/start_screen/start_screen_controller.dart
  lib/views/start_screen/start_screen_view_model.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#53 Better capture
  lib/views/capture_screen/capture_screen_view_model.dart
  lib/views/custom_widgets/capture_counter.dart
  lib/views/multi_capture_screen/multi_capture_screen_view_model.dart
Labels: enhancement

#64 Confetti 🎉✨
  lib/models/settings.dart
  lib/views/settings_screen/settings_screen_controller.dart
  lib/views/settings_screen/settings_screen_view.dart
  lib/views/settings_screen/settings_screen_view_model.dart
  lib/views/share_screen/share_screen_view.dart
  lib/views/share_screen/share_screen_view_model.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#72 Collage output and UX enhancements
  lib/main.dart
  lib/views/collage_maker_screen/collage_maker_screen_controller.dart
  lib/views/collage_maker_screen/collage_maker_screen_view.dart
  lib/views/collage_maker_screen/collage_maker_screen_view_model.dart
  lib/views/custom_widgets/photo_collage.dart
  lib/views/share_screen/share_screen_controller.dart
  lib/views/share_screen/share_screen_view.dart
  lib/views/share_screen/share_screen_view_model.dart
  lib/views/start_screen/start_screen_view.dart
Labels: enhancement

#75 Fix printing
  lib/models/settings.dart
  lib/views/settings_screen/settings_screen_controller.dart
  lib/views/settings_screen/settings_screen_view.dart
  lib/views/settings_screen/settings_screen_view_model.dart
  lib/views/share_screen/share_screen_controller.dart
Labels: bug, enhancement

#76 Live view fading
  lib/views/capture_screen/capture_screen_view_model.dart
  lib/views/custom_widgets/wrappers/live_view_background.dart
  lib/views/multi_capture_screen/multi_capture_screen_view_model.dart
Labels: bug

#78 Fix stuttering by collage
  lib/views/capture_screen/capture_screen_view.dart
  lib/views/custom_widgets/photo_collage.dart
Labels: bug

#82 Sony capture enhancement
  assets/bitmap/capture-error.png
  assets/scripts/sony_remote_capture_photo.au3
  lib/hardware_control/photo_capturing/live_view_stream_snapshot_capturer.dart
  lib/hardware_control/photo_capturing/sony_remote_photo_capture.dart
  lib/models/settings.dart
  lib/views/capture_screen/capture_screen_view_model.dart
  lib/views/multi_capture_screen/multi_capture_screen_view_model.dart
  lib/views/settings_screen/settings_screen_controller.dart
  lib/views/settings_screen/settings_screen_view.hardware.dart
  lib/views/settings_screen/settings_screen_view_model.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#83 Create & use image decoded callback in collage.
  lib/views/capture_screen/capture_screen_view.dart
  lib/views/capture_screen/capture_screen_view_model.dart
  lib/views/custom_widgets/photo_collage.dart
Labels: enhancement

#89 Collage sizing settings
  lib/models/settings.dart
  lib/views/capture_screen/capture_screen_view.dart
  lib/views/capture_screen/capture_screen_view_model.dart
  lib/views/collage_maker_screen/collage_maker_screen_view.dart
  lib/views/collage_maker_screen/collage_maker_screen_view_model.dart
  lib/views/custom_widgets/photo_collage.dart
  lib/views/settings_screen/settings_screen_controller.dart
  lib/views/settings_screen/settings_screen_view.general.dart
  lib/views/settings_screen/settings_screen_view.output.dart
  lib/views/settings_screen/settings_screen_view_model.dart
Labels: enhancement

#90 Print button gives more feedback
  lib/views/share_screen/share_screen_controller.dart
  lib/views/share_screen/share_screen_view.dart
  lib/views/share_screen/share_screen_view_model.dart
Labels: enhancement

#88 Add stats to Settings
  lib/main.dart
  lib/managers/live_view_manager.dart
  lib/managers/stats_manager.dart
  lib/models/stats.dart
  lib/views/capture_screen/capture_screen_view_model.dart
  lib/views/collage_maker_screen/collage_maker_screen_controller.dart
  lib/views/custom_widgets/pages/fluent_settings_page.dart
  lib/views/multi_capture_screen/multi_capture_screen_view_model.dart
  lib/views/settings_screen/settings_screen_view.dart
  lib/views/settings_screen/settings_screen_view.debug.dart
  lib/views/settings_screen/settings_screen_view.helpers.dart
  lib/views/share_screen/share_screen_controller.dart
Labels: enhancement
